CREATE TABLE SECURITY (
 EMPLOYEE_ID NUMBER(6) CONSTRAINT SECURITY_EMPLOYEE_ID_PK PRIMARY KEY
,SEC_ID VARCHAR2(20) CONSTRAINT SECURITY_SEC_ID_UK UNIQUE NOT NULL
,SEC_PASSWORD VARCHAR2(10) NOT NULL
,SEC_STATUS CHAR(1) CONSTRAINT SECURITY_SEC_STATUS_CHK CHECK(SEC_STATUS IN ('I', 'A')) NOT NULL
,CONSTRAINT SECURITY_EMPLOYEE_ID_FK FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE
)
;

INSERT INTO SECURITY 
( EMPLOYEE_ID, SEC_ID, SEC_PASSWORD, SEC_STATUS)
SELECT 201, 'servlet', 'servlt', 'I' FROM DUAL UNION ALL
SELECT 202, 'java', 'java', 'I' FROM DUAL UNION ALL
SELECT 203, 'hr', 'hr', 'A' FROM DUAL 
;
